### ISSUE TITLE
Your energy page id values are keep changing

### ISSUE THREAD

**Issue by asifAutomationRepo** [neilstudd/technical-tests#8]
Hello,

I've submitted my tech test this afternoon. Since I submitted my test ids in Your energy page are undergone some changes therefore my tests are failing now. 
I have fixed most of them (page object model to rescue). Basically change was ''_' replaced by "-" however some of the id looks like not yet changed in front-end.

I can submit my changes now. Is there any more update scheduled any time soon? 
I hope I won't get assessed for failed test beyond  my control :)

Kind regards
Asif

**Comment by neilstudd** [comment]
Hi Asif,

I'll speak to the Energy team to see what's happening here. Ironically maybe it's changing because they're in the middle of rewriting some automation!

You certainly won't be penalised for tests which are failing beyond your control - we are much more interested in clear/concise automation code. But if you're invited in for an interview, we'll try to run them beforehand, and you can expect to be questioned on the failures if there are any :) 

Thanks,
Neil
